apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project/platform.yaml
  - project/applications.yaml
  - application/platform-dev.yaml
  - application/application-demo-app.yaml
  - application/observability-kube-prometheus-stack.yaml
  - application/observability-loki.yaml
  - application/observability-alloy.yaml
