apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.28.0
    helm:
      releaseName: loki
      valueFiles:
        - $values/platform/observability/loki/base/values.yaml
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.28.0
      helm:
        releaseName: loki
        valueFiles:
          - $values/platform/observability/loki/base/values.yaml
    - repoURL: https://github.com/Adman-Corp/admancorp-platform-manifest.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
